let fibonacciSequence = [];
fibonacciSequence[0] = 0;
fibonacciSequence[1] = 1;
fibonacciSequence[2] = 1;
fibonacciSequence[3] = 2;
fibonacciSequence[4] = 3;
fibonacciSequence[5] = 5;
fibonacciSequence[6] = 8;
console.log(fibonacciSequence[0]);
console.log(fibonacciSequence[1]);
console.log(fibonacciSequence[2]);
console.log(fibonacciSequence[3]);
console.log(fibonacciSequence[4]);
console.log(fibonacciSequence[5]);
console.log(fibonacciSequence[6]);
